### ISSUE TITLE
[CI Optimization] Add a scheduled spec-test CI for MacOS

### ISSUE THREAD

**Issue by lum1n0us** [bytecodealliance/wasm-micro-runtime#1572]
```yml
on:
  schedule:
    # On 1 am everyday
    - cron:  '0 1 * * *'
```

Run a full feature spec test
| OS                 | defulat               | +multi module | +simd      | +thread              |
| ------------------ | --------------------- | ------------- | ---------- | -------------------- |
| macos              | INTERP(2)+JIT(L)+AOT  | INTERP(2)     | JIT(L)+AOT | INTERP(2)+JIT(L)+AOT |
